title: Yao Zhang
email: phoebeyao.zhang@gmail.com
description: >
  Professional website for research and technical work in
  data science, engineering, and complex systems.
url: https://feebsssz.github.io

markdown: kramdown
theme: minima

header_pages:
  - index.md
  - cv.md
  - experience.md
  - projects.md
  - skills.md
  - education.md
  - publications.md
